### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by luiyi99** [gkoberger/avataaars#17]
I have done all steps:
$ git clone git@github.com:gkoberger/avataaars.git
$ cd avataaars
$ npm install
$ npm start
but I get "Unexpected token {" error.
![immagine](https://user-images.githubusercontent.com/33969567/94338126-3d114f80-fff0-11ea-9b81-b428046c7a8f.png)

**Comment by gkoberger** [comment]
Hey! I was able to reproduce this using Node v8.9.0. Try upgrading to 10.

If you're worried about messing up other things, try using `nvm` and only using v10 for this project!

Let me know if you get stuck :)

**Comment by luiyi99** [comment]
> Hey! I was able to reproduce this using Node v8.9.0. Try upgrading to 10.
> 
> 
> 
> If you're worried about messing up other things, try using `nvm` and only using v10 for this project!
> 
> 
> 
> Let me know if you get stuck :)

Thank you very much, I was using docker assuming the version indicated in the dockerfile were correct.

**Comment by gkoberger** [comment]
Ah, I never upgraded it! FIxing :)
